language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION jupyter six pytest pip matplotlib sympy
  - source activate test-environment
  # $VIRTUAL_ENV is left over from the virtualenv Travis prepared. IPython will
  # see it and add the venv's site-packages to sys.path, which causes import
  # confusion. Therefore we unset it here.
  - unset VIRTUAL_ENV
  - pip install .

# command to run tests
script: py.test tests/ --nbval --current-env --sanitize-with tests/sanitize_defaults.cfg --ignore tests/ipynb-test-samples
