language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - unset VIRTUAL_ENV
  - pip install .
  # have some tests using sympy
  - pip install sympy
  # and some use matplotlib
  - pip install matplotlib

# command to run tests
script: make test
